---
- name: Run netplan to ensure routes are ok
  become: true
  ansible.builtin.command:
      cmd: netplan apply
  changed_when: false

- name: Run interface setup
  become: true
  ansible.builtin.command:
      cmd: '{{ if_setup }}'
  changed_when: false
